name: dns test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'macos-12', 'macos-13', 'ubuntu-latest']
        try: ['0', '1', '2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: nslookup
        shell: bash
        run: |
          echo -e "Expecting nslookup to return $(hostname -f)\n\n"
          for host in "$(hostname)" "$(hostname -f)"; do
              echo "nslookup $host: $(nslookup "$host" 2>&1 | grep -E '(Name:|\*\*)' || true)"
          done
